apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: checkpoints.ava.qiniu.com
spec:
  group: ava.qiniu.com
  names:
    kind: Checkpoint
    listKind: CheckpointList
    plural: checkpoints
    singular: checkpoint
    shortNames:
    - chp
  scope: Namespaced
  version: v1alpha1
  validations:
    openAPIV3Schema:
      properties:
        spec:
          required:
          - podName
          - containerName
          - imageName
          - imagePushSecret
          properties:
            podName:
              type: string
            containerName:
              type: string
            imageName:
              type: string
            imagePushSecret:
              required:
              - name
              properties:
                name:
                  type: string
